### ISSUE TITLE
PR to tensorflow

### ISSUE THREAD

**Issue by bhack** [rinuboney/ladder#7]
Can you open a WIP PR on Tensorflow?

**Comment by rinuboney** [comment]
I am sorry, I don’t understand. open a WIP PR on Tensorflow?

**Comment by bhack** [comment]
Yes i mean contribute a Work In Progress pull Request on Tensorflow (in example, tutorial of whereever you want). You have already a good blog post on this so I think it is better your propose a PR on the official Tensorflow repository.

**Comment by rinuboney** [comment]
you mean that I should send a WIP PR to add Ladder networks as an example/tutorial in the official TensorFlow repository?

**Comment by bhack** [comment]
Yes

**Comment by rinuboney** [comment]
How can I send a PR to the tensorflow repository (since this isn't a fork)?

**Comment by bhack** [comment]
You need to fork Tensorflow and open a new branch. There you'll organize your code and documentation so you can open the PR. If you reverse material from your blog post other than code probably you can organize as tutorial in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials
